name: spectrum-rgb

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: 
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  packages: write

jobs:
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup docker builds
        uses: docker/setup-buildx-action@v1
      
      - name: loging to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta
        id: spectrumrgb
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ampretia/spectrumrgb
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.spectrumrgb.outputs.tags }}
          labels: ${{ steps.spectrumrgb.outputs.labels }}
